[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = False
dbfilter = ^inmobiliaria_dev$
db_maxconn = 64
dev_mode = reload,qweb,werkzeug,xml
log_level = info
logfile = /var/log/odoo/odoo.log
log_handler = :INFO
log_db = False
log_db_level = warning
workers = 0
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
max_cron_threads = 1
admin_passwd = admin123
without_demo = False
unaccent = True
translate_modules = all
http_port = 8069
longpolling_port = 8072
proxy_mode = False